CREATE TABLE User(
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	password VARCHAR(256) NOT NULL,
	email VARCHAR(40),
	phone VARCHAR(10) NOT NULL,
	PRIMARY KEY (email)
);

CREATE TABLE Baguni(
	email VARCHAR(40),
	baguniid INTEGER NOT NULL AUTO_INCREMENT,
	title VARCHAR(20),
	color VARCHAR(7),
	PRIMARY KEY (baguniid),
	FOREIGN KEY (email) REFERENCES User(email) ON DELETE CASCADE
);

CREATE TABLE BaguniAccess(
	email VARCHAR(40) NOT NULL,
	baguniid INTEGER NOT NULL,
	FOREIGN KEY (baguniid) REFERENCES Baguni(baguniid) ON DELETE CASCADE,
	FOREIGN KEY (email) REFERENCES User(email) ON DELETE CASCADE
);

CREATE TABLE Item(
	baguniid INTEGER NOT NULL,
	itemid INTEGER NOT NULL AUTO_INCREMENT,
	originalurl VARCHAR(256),
	imageurl VARCHAR(256),
	price DECIMAL(7,2),
	brandname VARCHAR(20),
	itemname VARCHAR(40),
	quantity TINYINT(3),
	size VARCHAR(10),
	selected TINYINT(1),
	PRIMARY KEY (itemid),
	FOREIGN KEY (baguniid) REFERENCES Baguni(baguniid) ON DELETE CASCADE
);

CREATE TABLE ItemAccess(
	baguniid INTEGER NOT NULL,
	itemid INTEGER NOT NULL,
	FOREIGN KEY (baguniid) REFERENCES Baguni(baguniid) ON DELETE CASCADE,
	FOREIGN KEY (itemid) REFERENCES Item(itemid) ON DELETE CASCADE
);

